language: python
python:
    - 2.7
    - 3.4
    - 3.5
before_install:
    # Diag output
    - echo "before_install"
    - echo $VIRTUAL_ENV
    # Update system packages
    - sudo apt-get update -qq
    # Update pip to get wheel support
    - pip install --upgrade pip setuptools wheel
install:
    # Dependencies
    - pip install -r requirements.txt
    # Build the extension modules
    - python setup.py build_ext --inplace
    # Link into virtualenv
    - python setup.py develop
script:
    # Exclude regression and remote tests since they currently cause a fork bomb
    - nosetests -e "regression|remote" mdf/tests
